### ISSUE TITLE
TypeError after upgrading from 2.2.1 to 4.1.0

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.app.blocks#62]
After upgrading plone.app.blocks on a Plone 4.3.3 site and running the upgrade step, the following error is logged on the event log many times when accessing a collective.cover object:

```pytb
2017-11-30T23:51:10 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/home/example/foo/eggs/plone.transformchain-1.0.3-py2.7.egg/plone/transformchain/transformer.py", l
ine 48, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/home/example/foo/eggs/plone.app.blocks-4.1.0-py2.7.egg/plone/app/blocks/transform.py", line 166, in transformIterable
    result.tree = tiles.renderTiles(self.request, result.tree)
  File "/home/example/foo/eggs/plone.app.blocks-4.1.0-py2.7.egg/plone/app/blocks/tiles.py", line 73, in renderTiles
   tileTree = utils.resolve(tileHref)
  File "/home/example/foo/eggs/plone.app.blocks-4.1.0-py2.7.egg/plone/app/blocks/utils.py", line 73, in resolve
    resolved = resolveResource(url)
  File "/home/example/foo/eggs/plone.app.blocks-4.1.0-py2.7.egg/plone/app/blocks/utils.py", line 115, in resolveResource
    response = subrequest(url, exception_handler=subresponse_exception_handler)
TypeError: subrequest() got an unexpected keyword argument 'exception_handler'
```

Workaround is uninstall plone.app.block, downgrade to 2.2.1 and install again.

**Comment by datakurre** [comment]
it seems, we should pin minimum version of plone.subrequest in setup.py

**Comment by djowett** [comment]
Thanks. Not sure if it's best, but p.subrequest 1.7.0 seems to be working for me with this issue
